/**
 * Custom worker entry (wrangler.jsonc `main`): the SvelteKit-generated
 * worker only exposes `fetch`, so this module re-exports it and adds the
 * `scheduled()` handler for the Cron Trigger that sweeps scheduled tasks.
 *
 * It lives outside src/ so svelte-check doesn't follow the import into the
 * generated worker; wrangler bundles it itself (esbuild), outside the
 * SvelteKit build. That also means the import chain must avoid `$lib`/`$app`
 * aliases — see src/lib/server/schedule-sweep.ts. The adapter is pointed at
 * wrangler.adapter.jsonc (see vite.config.ts) so it keeps writing its
 * generated worker to .svelte-kit/cloudflare/_worker.js instead of
 * clobbering this file.
 */
import type { ExecutionContext, ScheduledController } from '@cloudflare/workers-types';
// @ts-ignore — generated by the SvelteKit build; absent until `pnpm build`.
import worker from '../.svelte-kit/cloudflare/_worker.js';
import { sweepSchedules } from '../src/lib/server/schedule-sweep';

export default {
	...worker,
	async scheduled(controller: ScheduledController, env: Env, _ctx: ExecutionContext) {
		await sweepSchedules(env, controller.scheduledTime || Date.now());
	}
};
