/**
 * Custom worker entry (wrangler.jsonc `main`): the SvelteKit-generated
 * worker only exposes `fetch`, so this module re-exports it and adds the
 * `scheduled()` handler for the Cron Trigger that sweeps scheduled tasks.
 *
 * It lives outside src/ so svelte-check doesn't follow the import into the
 * generated worker; wrangler bundles it itself (esbuild), outside the
 * SvelteKit build. That also means the import chain must avoid `$lib`/`$app`
 * aliases — see src/lib/server/schedule-sweep.ts. The adapter is pointed at
 * wrangler.adapter.jsonc (see vite.config.ts) so it keeps writing its
 * generated worker to .svelte-kit/cloudflare/_worker.js instead of
 * clobbering this file.
 */
import type { ExecutionContext, ScheduledController } from '@cloudflare/workers-types';
// @ts-ignore — generated by the SvelteKit build; absent until `pnpm build`.
import worker from '../.svelte-kit/cloudflare/_worker.js';
import { getDb } from '../src/lib/server/db';
import { sweepSchedules } from '../src/lib/server/schedule-sweep';
import { sweepSupervisor } from '../src/lib/server/supervisor/engine';
import { sweepModerationRetention } from '../src/lib/server/publications/moderation-retention';
import { handlePublicationFetch } from '../src/lib/server/publications/response';
import { handleDeploymentFetch } from '../src/lib/server/deployment-response';
import deploymentIdentity from '../.generated/deployment.json';

export default {
	...worker,
	async fetch(request: Request, env: Env, ctx: ExecutionContext) {
		return handleDeploymentFetch(
			request,
			(deploymentRequest) =>
				handlePublicationFetch(deploymentRequest, (prepared) => {
					// The isolated E2E Worker can force outcomes the generated SvelteKit
					// entry normally absorbs. This keeps the shipping outer wrapper
					// behaviorally pinned without exposing a production trigger.
					if (env.E2E_PUBLICATION_BOUNDARY_TEST === '1') {
						const mode = prepared.headers.get('x-tines-e2e-publication-boundary');
						if (mode === 'throw') throw new Error('e2e generated Worker failure');
						if (mode === '304')
							return Promise.resolve(new Response(null, { status: 304, headers: { etag: 'e2e' } }));
					}
					return worker.fetch(prepared, env, ctx);
				}),
			deploymentIdentity
		);
	},
	async scheduled(controller: ScheduledController, env: Env, _ctx: ExecutionContext) {
		const now = controller.scheduledTime || Date.now();
		let failure: unknown;
		try {
			// Schedules first: an instance created here is dispatchable in the
			// supervisor sweep that follows in the same firing.
			await sweepSchedules(env, now);
			await sweepSupervisor(getDb(env), env, now);
		} catch (error) {
			failure = error;
		} finally {
			try {
				const result = await sweepModerationRetention(env, now);
				if (result.deleted) console.info('Moderation retention cleanup', result);
			} catch {
				console.error('Moderation retention cleanup failed', { code: 'moderation_cleanup_failed' });
			}
		}
		if (failure) throw failure;
	}
};
